# Generated by Django 2.1.2 on 2018-11-06 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guestFirstName',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guestLastName',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='no',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
