# Generated by Django 2.1.2 on 2018-11-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20181106_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guestFirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='guestLastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.Room'),
        ),
    ]
