# Generated by Django 2.1.2 on 2018-11-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20181107_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='CheckIn',
            new_name='checkIn',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='CheckOut',
            new_name='checkOut',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.Guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.Room'),
        ),
    ]
