# Generated by Django 2.1.2 on 2018-11-07 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20181107_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='no',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
