# Generated by Django 2.1.2 on 2018-11-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_auto_20181107_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='person',
        ),
    ]
