# Generated by Django 2.1.2 on 2018-11-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_auto_20181107_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='person',
            new_name='guest',
        ),
    ]
