# Generated by Django 2.1.2 on 2018-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_auto_20181107_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
