# Generated by Django 2.1.2 on 2018-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_auto_20181107_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
